# MkDocs configuration for the developer docs microsite.
site_name: HuggingFace Hands-On Cookbook
repo_url: https://github.com/SSusantAchary/HuggingFace-HandsOn-Cookbook
repo_name: HuggingFace-HandsOn-Cookbook
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - search.highlight
    - search.suggest
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SSusantAchary/HuggingFace-HandsOn-Cookbook
nav:
  - Home: docs/index.md
  - Notebook Gallery: docs/gallery.md
  - Fixes & Tips: docs/fixes-and-tips.md
  - Ecosystem: docs/ecosystem.md
  - Benchmark Highlights: docs/benchmarks.md
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.superfences
plugins:
  - search
